# Generated by Django 5.1.3 on 2025-06-18 02:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_aichatsession_airequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='airequest',
            name='messages',
            field=models.JSONField(default=[]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='airequest',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.aichatsession'),
        ),
    ]
